language: ruby
bundler_args: --without development
rvm:
  - 1.9.2
  - 1.9.3
before_script:
  - "psql -c 'create database latter_test;' -U postgres"
  - "ln -s config/database.yml.example config/database.yml"
script: RAILS_ENV=test bundle exec rake db:migrate db:test:prepare spec
