language: ruby
bundler_args: --without development
rvm:
  - 2.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
before_script:
  - "cp config/database.yml.example config/database.yml"
  - "psql -c 'create database latter_test;' -U postgres"
script: RAILS_ENV=test bundle exec rake db:migrate db:test:prepare spec
